### PR TITLE
Updated multistage-delivery.sh for examples with correct tags

### PR DESCRIPTION
**Pull request by indraindrajit71**
Updated multistage-delivery.sh for examples with correct tags

## This PR

- adds this new feature

### Related Issues

Fixes #1234523

### CODE REVIEW

**Comment by christian-kreuzberger-dtx** [comment]
Code changes are okay!
FYI, this will not work with Keptn 0.14.x because of this bug: https://github.com/keptn/keptn/issues/7368
It has been fixed in 0.15.x though.

**Review by thisthat — APPROVED** [review]

**Comment by thisthat** [comment]
Hi @indraindrajit71, could you please update your commit and sign it? You can follow a guide here: https://github.com/keptn/examples/pull/233/checks

**Comment by oleg-nenashev** [comment]
#234 consumes it

**Comment by DavidPHirsch** [comment]
outdated

**Pull request closed without merging**
